// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "imageProcessor/internal/models"

	uuid "github.com/google/uuid"
)

// ImageGetter is an autogenerated mock type for the ImageGetter type
type ImageGetter struct {
	mock.Mock
}

// GetImage provides a mock function with given fields: ctx, id
func (_m *ImageGetter) GetImage(ctx context.Context, id uuid.UUID) (*models.Image, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 *models.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Image, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Image); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageGetter creates a new instance of ImageGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageGetter {
	mock := &ImageGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
