// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ImageDeleter is an autogenerated mock type for the ImageDeleter type
type ImageDeleter struct {
	mock.Mock
}

// DeleteImage provides a mock function with given fields: ctx, id
func (_m *ImageDeleter) DeleteImage(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImageDeleter creates a new instance of ImageDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageDeleter {
	mock := &ImageDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
